cargo-features = ["edition2024"]

[package]
name = "solana-2"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
solana-program = "2.3.0"

[dev-dependencies]
solana-program-test = "2.3.0"
solana-sdk = "2.3.0"